/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WaitlistEntry = IDL.Record({
  'email' : IDL.Text,
  'companyName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllEntries' : IDL.Func([], [IDL.Vec(WaitlistEntry)], ['query']),
  'getWaitlistCount' : IDL.Func([], [IDL.Nat], ['query']),
  'joinWaitlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WaitlistEntry = IDL.Record({
    'email' : IDL.Text,
    'companyName' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllEntries' : IDL.Func([], [IDL.Vec(WaitlistEntry)], ['query']),
    'getWaitlistCount' : IDL.Func([], [IDL.Nat], ['query']),
    'joinWaitlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };